### ISSUE TITLE
这是一个基本讨论串

### ISSUE THREAD

**Issue by jiangming1399** [GDUT-Drcom/Drcom-Dialer#1]
首先、我们需不需要兼容XP，用低版本的.Net运行库？
第二、如果不兼容，那么用传统界面还是用WPF？
第三、谁来建立工程？
第四、用什么方式引用心跳包的那个项目？
第五、用什么开源协议？

**Comment by jiangming1399** [comment]
我的意见是兼容、使用GPL协议

**Comment by lindexi** [comment]
只需要用.net FrameWork 4.0以下就可以在xp跑
WPF可以用，但是心跳包的直接引用就好
开源协议GPL

**Comment by chenhaowen01** [comment]
老实说，xp还有人用吗
工程让你们熟悉c#的来，c#我基本不懂

**Comment by lindexi** [comment]
xp就是用.net 3.5可以用，但是我不做xp

**Comment by jiangming1399** [comment]
我还真有两个同学在用。。。。对于XP，我觉得还是兼容，但是不提供支持就好

**Comment by lindexi** [comment]
那么需要用.net 3.5

**Comment by jiangming1399** [comment]
就算是3.5，有些电脑也要下载支持库。我觉得可能2.0会比较合适

**Comment by lindexi** [comment]
我几乎不会写，太久了

**Comment by jiangming1399** [comment]
应该没有什么太大的区别的

**Comment by lindexi** [comment]
很大，我现在用 461

**Comment by jiangming1399** [comment]
好吧 那就用3.5吧

**Comment by lindexi** [comment]
我觉得做两个项目好

**Comment by jiangming1399** [comment]
弄个分支咯

**Comment by lindexi** [comment]
分支叫什么？

**Comment by jiangming1399** [comment]
Master是3.5版本
再新建一个名称为DotNet20的分支

**Comment by jiangming1399** [comment]
@lindexi 你来建立工程吧，你比较熟

**Comment by lindexi** [comment]
MVVM

**Comment by jiangming1399** [comment]
你弄个贡献指南

**Comment by lindexi** [comment]
表示最近好忙

**Comment by lindexi** [comment]
我写不出贡献，只能把我之前的改下建工程，其他需要大神帮忙

**Comment by jiangming1399** [comment]
最好新建一个工程，不要用之前的dialer的代码，或者至少重写一遍

**Comment by lindexi** [comment]
这样也好

**Comment by lindexi** [comment]
@jiangming1399 必须你创建工程，因为我权限没有 ![](http://ooo.0o0.ooo/2016/11/16/582c16f4935c7.jpg)

**Comment by lindexi** [comment]
我的代码：https://github.com/lindexi/PPPoE-Dialer/tree/dialer

**Comment by jiangming1399** [comment]
@lindexi 给你权限了。之前没有改默认权限

话说今天Github真的炸的可以

**Comment by chenhaowen01** [comment]
要通过命令行的形式调用gdut-drcom，还是通过c库

**Comment by jiangming1399** [comment]
最好是dll之类的东西吧，方便更新

**Comment by chenhaowen01** [comment]
ok

**Comment by lindexi** [comment]
我觉得用dll也是比较好，可以建立工程

**Comment by lindexi** [comment]
听说 @jiangming1399 在16号有更新心跳包，我就建立了一个空工程，核心靠你了

**Comment by jiangming1399** [comment]
@lindexi 做下拨号逻辑吧 心跳要等@chenhaowen01弄好dll才行

**Comment by lindexi** [comment]
拨号的，原先的版本的出现拨号异常，你知不知原因

**Comment by chenhaowen01** [comment]
dll我昨晚试过编译了一次，我用python测试能成功调用，在c#下是什么情况还要你们测试

**Comment by jiangming1399** [comment]
@lindexi 什么拨号异常？

**Comment by jiangming1399** [comment]
@chenhaowen01 能否提供如下接口
- 当前版本号
- 错误代码（如果心跳错误）
还有可不可以将初始化和心跳主过程分离

**Comment by lindexi** [comment]
就是我的版本有部分说拨号异常

**Comment by jiangming1399** [comment]
不是很清楚问题在哪，要是能提供日志就好了，按理说各个拨号器都是一样的，一个能用另一个也能用才对。

之前我的一个同学开官方的拨号器和我的那个拨号器都闪退，原因未知，最后只好重装系统。

**Comment by chenhaowen01** [comment]
gdut-drcom可以提供 修改配置用的全局变量（也可以通过一组函数提供），心跳启动函数。

**Comment by jiangming1399** [comment]
@chenhaowen01 还是不知道你把改过的代码放哪了2333你的那个库里面找不到。要不直接给个binary也行
   
@lindexi 起来做拨号逻辑啦

**Comment by lindexi** [comment]
在外面……

**Comment by lyhyl** [comment]
大家只是想做大学城专版？我本人是龙洞的，我觉得可以做个选项，第一次启动的时候询问是哪个校区的。龙洞的只是认证地址是10.0.3.6，pppoe_flag=6a，keep_alive2_flag=dc而已……心跳包应该是一样的，我用的是[lastest-pppoe.py](https://github.com/drcoms/drcom-generic/blob/master/latest-pppoe.py)。

还有VPN修复方面，能不能贴一下你们在cmd下route print的结果？

**Comment by chenhaowen01** [comment]
代码还没提交，其实根本就没改。重新编译链接而已。

**Comment by chenhaowen01** [comment]
gdut-drcom是可以龙洞使用，海峡配置文件，或者通过命令行配置。

**Comment by jiangming1399** [comment]
龙洞要兼容很简单的，改下认证IP就可以了

**Comment by jiangming1399** [comment]
还有我们可能需要一个配置页面了，看上去要设置的东西有点多了

**Comment by lindexi** [comment]
做个设置页面

**Comment by chenhaowen01** [comment]
我提交了gdut-drcom的代码，Makefile添加了一个目标dll，通过
`make dll`
来编译生成dll。
提供如下接口供修改配置以及调用心跳函数：
`void set_remote_ip(char *ip, int len);    //设置认证服务器ip
void set_keep_alive1_flag(char *flag, int len);    //设置keep_alive1_flag，默认为00
void set_enable_crypt(int enable);    //启用加密验证，默认为0
int auth(void);    //心跳`

**Comment by chenhaowen01** [comment]
@jiangming1399 需要我提供dll文件吗，还是你们自行编译

**Comment by chenhaowen01** [comment]
我测试用的python代码，供参考
```python
#!/usr/bin/env python3

import ctypes

gdut_drcom = ctypes.cdll.LoadLibrary(".\gdut-drcom")

ip = b"10.0.3.2"
gdut_drcom.set_remote_ip(ip, len(ip))
gdut_drcom.set_enable_crypt(1)

gdut_drcom.auth()
```

**Comment by jiangming1399** [comment]
下次给个版本号接口吧，方便在线更新

**Comment by chenhaowen01** [comment]
可以

**Comment by lindexi** [comment]
@jiangming1399  DotRas 是哪个版本？

**Comment by lindexi** [comment]
我修改了一些命名和提出一些建议，还有在窗体修改一点可能因为null出现的bug

**Comment by lindexi** [comment]
@jiangming1399 好厉害，界面漂亮

**Comment by lyhyl** [comment]
求route print结果😳 @jiangming1399 @lindexi @chenhaowen01 我把VPNFix写上吧，看看gateway是不是都是172.18.0.1

**Comment by jiangming1399** [comment]
```
活动路由:
网络目标        网络掩码          网关       接口   跃点数
          0.0.0.0          0.0.0.0      192.168.2.1    192.168.2.144     25
        127.0.0.0        255.0.0.0            在链路上         127.0.0.1    331
        127.0.0.1  255.255.255.255            在链路上         127.0.0.1    331
  127.255.255.255  255.255.255.255            在链路上         127.0.0.1    331
      169.254.0.0      255.255.0.0            在链路上   169.254.192.176    281
  169.254.192.176  255.255.255.255            在链路上   169.254.192.176    281
  169.254.255.255  255.255.255.255            在链路上   169.254.192.176    281
      192.168.2.0    255.255.255.0            在链路上     192.168.2.144    281
    192.168.2.144  255.255.255.255            在链路上     192.168.2.144    281
    192.168.2.255  255.255.255.255            在链路上     192.168.2.144    281
        224.0.0.0        240.0.0.0            在链路上         127.0.0.1    331
        224.0.0.0        240.0.0.0            在链路上   169.254.192.176    281
        224.0.0.0        240.0.0.0            在链路上     192.168.2.144    281
  255.255.255.255  255.255.255.255            在链路上         127.0.0.1    331
  255.255.255.255  255.255.255.255            在链路上   169.254.192.176    281
  255.255.255.255  255.255.255.255            在链路上     192.168.2.144    281
```

接了路由
```
root@lede:~# route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         10.30.96.1      0.0.0.0         UG    0      0        0 pppoe-PPPOE
10.30.96.1      *               255.255.255.255 UH    0      0        0 pppoe-PPPOE
172.17.0.0      *               255.255.128.0   U     0      0        0 eth0.2
172.17.0.1      *               255.255.255.255 UH    0      0        0 eth0.2
192.168.2.0     *               255.255.255.0   U     0      0        0 br-lan
192.168.3.0     192.168.2.199   255.255.255.0   UG    0      0        0 br-lan
```

**Comment by jiangming1399** [comment]
@lindexi 1.3版本的

**Comment by jiangming1399** [comment]
@lindexi 我附上了DLL，在Reource文件夹，你看看怎么用吧

**Comment by lindexi** [comment]
@jiangming1399 研究下，静态他一个，我觉得就可以了，需要在运行检测存在不存在dll，程序目录。如果不存在，就移动到程序目录，我需要做一个启动界面，这个界面在程序读取配置后再跳转MainWindows。我们有两个MainWindows，我想把一个删了，解决方案里面那个。还有关于页面和设置都是控件，我想把它放在View/Control。

**Comment by jiangming1399** [comment]
@lindexi 我的想法是弄个自动更新系统，版本过低/不存在DLL都自动下载到目录下。

**Comment by lindexi** [comment]
可以，检查github txt，存在高版本，下载

2016-11-22 

lindexi_gd 



发件人：Jim Jiang <notifications@github.com>
发送时间：2016-11-22 16:21
主题：Re: [GDUT-Drcom/Drcom-Dialer] 这是一个基本讨论串 (#1)
收件人："GDUT-Drcom/Drcom-Dialer"<Drcom-Dialer@noreply.github.com>
抄送："lindexi"<lindexi_gd@163.com>,"Mention"<mention@noreply.github.com>

@lindexi 我的想法是弄个自动更新系统，版本过低/不存在DLL都自动下载到目录下。

**Comment by jiangming1399** [comment]
为什么要做个启动界面？觉得现在的方案好像还可以啊？

设置和关于界面你丢Control也行

**Comment by chenhaowen01** [comment]
我也得自动更新好啊

**Comment by lindexi** [comment]
如果一开始检查存在dll，不存在就写入dll，开始打开会慢，于是就可以尝试做启动页面。现在是启动快我们不觉得。

2016-11-22 

lindexi_gd 



发件人：Jim Jiang <notifications@github.com>
发送时间：2016-11-22 18:15
主题：Re: [GDUT-Drcom/Drcom-Dialer] 这是一个基本讨论串 (#1)
收件人："GDUT-Drcom/Drcom-Dialer"<Drcom-Dialer@noreply.github.com>
抄送："lindexi"<lindexi_gd@163.com>,"Mention"<mention@noreply.github.com>

为什么要做个启动界面？觉得现在的方案好像还可以啊？
设置和关于界面你丢Control也行

**Comment by jiangming1399** [comment]
所以我的想法是，PPPoE拨号后大约有1分钟的时间不断网，用这段时间来下载、更新、载入心跳包的DLL，

**Comment by lindexi** [comment]
开始拨号就需要dll

2016-11-22 

lindexi_gd 



发件人：Jim Jiang <notifications@github.com>
发送时间：2016-11-22 19:56
主题：Re: [GDUT-Drcom/Drcom-Dialer] 这是一个基本讨论串 (#1)
收件人："GDUT-Drcom/Drcom-Dialer"<Drcom-Dialer@noreply.github.com>
抄送："lindexi"<lindexi_gd@163.com>,"Mention"<mention@noreply.github.com>

所以我的想法是，PPPoE拨号后大约有1分钟的时间不断网，用这段时间来下载、更新、载入心跳包的DLL，

**Comment by jiangming1399** [comment]
不需要啊，为何需要呢？

**Comment by lindexi** [comment]
RasDialer是需要载入dll

2016-11-22 

lindexi_gd 



发件人：Jim Jiang <notifications@github.com>
发送时间：2016-11-22 19:57
主题：Re: [GDUT-Drcom/Drcom-Dialer] 这是一个基本讨论串 (#1)
收件人："GDUT-Drcom/Drcom-Dialer"<Drcom-Dialer@noreply.github.com>
抄送："lindexi"<lindexi_gd@163.com>,"Mention"<mention@noreply.github.com>

不需要啊，为何需要呢？

**Comment by jiangming1399** [comment]
可以打包成单exe

**Comment by lindexi** [comment]
DotRas有win7的 win8的，最好根据系统判断，这样开始就判断dll存在

2016-11-22 

lindexi_gd 



发件人：Jim Jiang <notifications@github.com>
发送时间：2016-11-22 19:59
主题：Re: [GDUT-Drcom/Drcom-Dialer] 这是一个基本讨论串 (#1)
收件人："GDUT-Drcom/Drcom-Dialer"<Drcom-Dialer@noreply.github.com>
抄送："lindexi"<lindexi_gd@163.com>,"Mention"<mention@noreply.github.com>

可以打包成单exe

**Comment by jiangming1399** [comment]
你可以自行生成Release试试，只需单个主程序即可运行。

dotras系统版本似乎是兼容的，不然之前那个客户端是怎么做的？

**Comment by lindexi** [comment]
不确定我的程序拨号异常因为DotRas版本问题
单个程序可以运行是因为我们用Nuget，本机有库。
打包请用 https://www.microsoft.com/en-us/download/details.aspx?id=17630

2016-11-22 

lindexi_gd 



发件人：Jim Jiang <notifications@github.com>
发送时间：2016-11-22 20:02
主题：Re: [GDUT-Drcom/Drcom-Dialer] 这是一个基本讨论串 (#1)
收件人："GDUT-Drcom/Drcom-Dialer"<Drcom-Dialer@noreply.github.com>
抄送："lindexi"<lindexi_gd@163.com>,"Mention"<mention@noreply.github.com>

你可以自行生成Release试试，只需单个主程序即可运行。
dotras系统版本似乎是兼容的，不然之前那个客户端是怎么做的？

**Comment by jiangming1399** [comment]
你大可以打包完复制到其他电脑试试。我已经添加了Costura.Fody包

**Comment by lindexi** [comment]
如果不附加dll的话，程序会在C:\windows\system32 下寻找，使用函数是引用dll的时候。

如果找不到，就会报异常，如FileNotFound或dll丢失，但不清楚你的打包表示的是把dll嵌入程序还是直接Release使用清单打包的方法。

Release有清单打包，我使用过了，但是一个安装版的。

因为我总是做很多垃圾软件，想要找个人来试我的软件没那么容易。
2016-11-22 

lindexi_gd 



发件人：Jim Jiang <notifications@github.com>
发送时间：2016-11-22 20:07
主题：Re: [GDUT-Drcom/Drcom-Dialer] 这是一个基本讨论串 (#1)
收件人："GDUT-Drcom/Drcom-Dialer"<Drcom-Dialer@noreply.github.com>
抄送："lindexi"<lindexi_gd@163.com>,"Mention"<mention@noreply.github.com>

你大可以打包完复制到其他电脑试试。我已经添加了Costura.Fody包

**Comment by jiangming1399** [comment]
Costura.Fody的作用类似于你发的那个ILMerge，所以不必担心打包问题

关于Dotras的版本问题，我刚刚去翻了下Faq，发现不同版本是功能和系统兼容性有区别。如果我们使用WIN8版本，那么最低系统要求就是Win8；如果我们使用2K8版本，那么最低系统要求就是Vista。反正这个拨号器没用到什么高级功能，直接用低版本的兼容到Vista或Win7就行.

**Comment by lindexi** [comment]
见识了，多谢

2016-11-22 

lindexi_gd 



发件人：Jim Jiang <notifications@github.com>
发送时间：2016-11-22 20:17
主题：Re: [GDUT-Drcom/Drcom-Dialer] 这是一个基本讨论串 (#1)
收件人："GDUT-Drcom/Drcom-Dialer"<Drcom-Dialer@noreply.github.com>
抄送："lindexi"<lindexi_gd@163.com>,"Mention"<mention@noreply.github.com>

Costura.Fody的作用类似于你发的那个ILMerge，所以不必担心打包问题
关于Dotras的版本问题，我刚刚去翻了下Faq，发现不同版本是功能和系统兼容性有区别。如果我们使用WIN8版本，那么最低系统要求就是Win8；如果我们使用2K8版本，那么最低系统要求就是Vista。反正这个拨号器没用到什么高级功能，直接用低版本的兼容到Vista或Win7就行.

**Comment by lindexi** [comment]
原来是版本兼容，那么Dotras问题就不大了。

关于自动更新，你是希望使用Git来做还是自己搭服务器来做

**Comment by jiangming1399** [comment]
我们的DLL更新是用GitHub Release + API 还是用Web？

API就方便，@chenhaowen01 放个Release就能更新，但是会受到Amazon服务被墙的影响
Web就没那么方便，要手工改文件

我有个服务器可以用，也可以用GithubPages，看你们怎么选咯

**Comment by lindexi** [comment]
其实你也可以内网搭服务器，这样还可以统计有多少 人在用。

Web的话，用GitPage做首页也是不错。

GitHub有时候不能访问

**Comment by jiangming1399** [comment]
内网无法互通啊2333

**Comment by lindexi** [comment]
忘了龙洞

**Comment by lyhyl** [comment]
我对dev push了，要不我们开个Q群吧……

**Comment by lindexi** [comment]
我觉得好，这样回复有点慢

**Comment by jiangming1399** [comment]
你们开个吧
这样真的难受

**Comment by lindexi** [comment]
StatusBar我添加的那句话是为了免责声明，询问了法律，我们算是非法破解，但是如果是内部使用就没关系，我对学校节操不抱希望。

我曾经就破解过人家软件被投诉

如果觉得加在那里丑，可以加到关于

**Comment by jiangming1399** [comment]
加关于也行吧，状态栏放那么长的东西真的丑（

**Comment by lindexi** [comment]
反正拨号后就覆盖了

**Comment by lyhyl** [comment]
Q群559425080

**Comment by jiangming1399** [comment]
关了吧关了吧
