### ISSUE TITLE
能不能改一下图标，亲

### ISSUE THREAD

**Issue by 2165998** [GDUT-Drcom/Drcom-Dialer#16]
**在报告问题前，请先阅读上方的wiki中的相关条目**

**如果你想要让你的问题尽快解决，请填写下面的内容**

* 操作系统：win7
* 软件版本：

### 问题的表现
不要单身狗，源码编译失败，明明nuget各种包已经下载，提示
XML 命名空间“clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro”中不存在标记“MetroWindow”，无解！！！
### 相关的软件日志
你可以使用下面的附件功能上传，或者直接在下面贴出软件日志。

```
在这里贴日志
```

**Comment by lindexi** [comment]
实际上把项目用git 重新克隆，之后设置cnblogs的nuget就可以编译

**Comment by 2165998** [comment]
由于没学C#，我临时用SharpDevelop的........

**Comment by lindexi** [comment]
原来这样，我加上如何编译

**Comment by 2165998** [comment]
谢谢你啦 哈哈
