### ISSUE TITLE
总是提示DLL缺失并且更新失败.

### ISSUE THREAD

**Issue by ThudrK** [GDUT-Drcom/Drcom-Dialer#23]
**在报告问题前，请先阅读上方的wiki中的相关条目**

**如果你想要让你的问题尽快解决，请填写下面的内容**

* 操作系统：WIN10
* 软件版本：1.0.4.146

### 问题的表现
登陆时提示DLL缺失并且更新失败.然后确实过一会就掉线了,是存DLL文件的服务器连不上,下载不到,所以缺文件了吗?
### 如何复现问题
重新运行一遍软件登陆,还会提示.
### 相关的软件日志
你可以使用下面的附件功能上传，或者直接在下面贴出软件日志。

```
在这里贴日志
```

**Comment by jim-kirisame** [comment]
之前服务器迁移的时候配置错了，现在应该可以正常更新了。
