### ISSUE TITLE
好像换心跳包了

### ISSUE THREAD

**Issue by Childlove** [GDUT-Drcom/Drcom-Dialer#24]
**在报告问题前，请先阅读上方的wiki中的相关条目**

**如果你想要让你的问题尽快解决，请填写下面的内容**

* 操作系统：win10
* 软件版本：

### 相关的软件日志
你可以使用下面的附件功能上传，或者直接在下面贴出软件日志。

```
在这里贴日志
```

**Comment by jim-kirisame** [comment]
是的，好像换心跳包了
ref: https://github.com/chenhaowen01/gdut-drcom/issues/8

但是也有报告官方拨号器也没法拨号的问题，还需要进一步观察。

(此项目维护者已经毕业，所以……只能等在校的同学修好开Pr了）

**Comment by Frenqy** [comment]
抓包发现心跳包是偶尔发生变化？我发了个issue在drcom-generic，详细描述和抓包/日志都在里面了
不知道怎么引用过来 所以发链接：[issue](https://github.com/drcoms/drcom-generic/issues/347#issue-495897512)

**Comment by purerosefallen** [comment]
Unfortunately, I even can't connect with the official Dr.COM client.
I attempted to run the official client in a KVM virtual machine running Windows 10, but the problem being disconnected every 2 mins remained.
I even tried with my roommate's account, but still not working. However, the problem didn't occur with my roommate's computer.
In addition, it worked when I tried to change the VM's MAC address to the same as my roommate's. However, it still didn't work when I switched MAC address to a random one. I wonder if there is a bind between the account and MAC address.
Looking for help.

**Comment by purerosefallen** [comment]
In addition, when the problem occurred, I asked my roommates if they had recently redownloaded the official Dr.COM client. However, they said no.
I still wonder how their clients work without any problem. Is there an auto update mechanic?

**Comment by Frenqy** [comment]
@purerosefallen  whats your DrCOM client version for Windows10? how about using official Dr.COM linux client from "http://222.200.98.8:1800/Dr.COM" ?

**Comment by Childlove** [comment]
version&nbsp; 1.0.4.146
IT&nbsp;is&nbsp;bad




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "MCsentic"<notifications@github.com&gt;; 
发送时间: 2019年9月20日(星期五) 上午9:45
收件人: "GDUT-Drcom/GDUT-Drcom-Dialer"<GDUT-Drcom-Dialer@noreply.github.com&gt;; 
抄送: "Childish"<2638182062@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [GDUT-Drcom/GDUT-Drcom-Dialer] 好像换心跳包了 (#24)




@purerosefallen  whats your DrCOM client version for Windows10? how about using official Dr.COM linux client from "http://222.200.98.8:1800/Dr.COM" ?
 
&mdash;

**Comment by eezhoukeyi** [comment]
> 是的，好像换心跳包了
> ref: [chenhaowen01/gdut-drcom#8](https://github.com/chenhaowen01/gdut-drcom/issues/8)
> 
> 但是也有报告官方拨号器也没法拨号的问题，还需要进一步观察。
> 
> (此项目维护者已经毕业，所以……只能等在校的同学修好开Pr了）

官方拨号器版本5.2.0p或5.2.1p都会90s一断，版本号6.0.0p的全部正常，亲测。

**Comment by lyhyl** [comment]
> > 是的，好像换心跳包了
> > ref: [chenhaowen01/gdut-drcom#8](https://github.com/chenhaowen01/gdut-drcom/issues/8)
> > 但是也有报告官方拨号器也没法拨号的问题，还需要进一步观察。
> > (此项目维护者已经毕业，所以……只能等在校的同学修好开Pr了）
> 
> 官方拨号器版本5.2.0p或5.2.1p都会90s一断，版本号6.0.0p的全部正常，亲测。

那基本上是换了心跳包了（甚至是认证方式），有能力的可以抓个正常的包看看。
参考:
[drcom-generic](https://github.com/drcoms/drcom-generic)
[drcom-generic wiki](https://github.com/drcoms/drcom-generic/wiki/p%E7%89%88%E7%AE%80%E7%95%A5%E4%BD%BF%E7%94%A8%E5%92%8C%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E)

**Comment by Frenqy** [comment]
> > > 是的，好像换心跳包了
> > > ref: [chenhaowen01/gdut-drcom#8](https://github.com/chenhaowen01/gdut-drcom/issues/8)
> > > 但是也有报告官方拨号器也没法拨号的问题，还需要进一步观察。
> > > (此项目维护者已经毕业，所以……只能等在校的同学修好开Pr了）
> > 
> > 
> > 官方拨号器版本5.2.0p或5.2.1p都会90s一断，版本号6.0.0p的全部正常，亲测。
> 
> 那基本上是换了心跳包了（甚至是认证方式），有能力的可以抓个正常的包看看。
> 参考:
> [drcom-generic](https://github.com/drcoms/drcom-generic)
> [drcom-generic wiki](https://github.com/drcoms/drcom-generic/wiki/p%E7%89%88%E7%AE%80%E7%95%A5%E4%BD%BF%E7%94%A8%E5%92%8C%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E)

感觉是心跳认证发生了改变，跟旧版抓包比较发现多了几步
详情可以看我在drcom-generic发的issue（可惜并没有人回应）
[抓包文件](https://github.com/GDUT-Drcom/GDUT-Drcom-Dialer/files/3634903/long.zip)

**Comment by purerosefallen** [comment]
@MCsentic 
1. The latest one. I just downloaded a brand-new one right before the test.
2. Completely broken. The official Linux Dr.COM client is for RedHat while my laptop is Ubuntu. In addition, it was still not working even with CentOS 7 VM. It's a client version 1.0.0p.

**Comment by Frenqy** [comment]
有部分同学反映从今天下午开始 在未进行任何操作的情况下 网络恢复了正常（keep_alive2_flag为\x2f)
有可能是昨天心跳包验证服务器出问题了
 ~~我待会儿回到宿舍会验证一下~~
已验证  \x2f 心跳包恢复正常 \x6a需要查证
不过当前项目的flag还是5.2.0p时代的\x6a（在之前试过是两个flag都可以完成心跳验证的），可能需要更新

**Comment by driver1998** [comment]
gdut-drcom用户，刚刚路由器上试了五分钟还没掉线，可能已经恢复正常了

**Comment by purerosefallen** [comment]
@MCsentic 
`\x2f` should be for the main campus. How about Longdong campus?

**Comment by Maalau** [comment]
好像现在路由器不会一分半断 但是还是会间歇性断 不稳定

**Comment by Frenqy** [comment]
@purerosefallen 
sorry ,i dont know. you can try previous argument and program. My roommate's network get right without any change.
Maybe you can get argument youeself follow [this](https://github.com/drcoms/drcom-generic/wiki/p%E7%89%88%E7%AE%80%E7%95%A5%E4%BD%BF%E7%94%A8%E5%92%8C%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E)

**Comment by jim-kirisame** [comment]
嘛，看上去暂时是稳定下来了，我就先close这个issue了。如果之后出现了新的情况的话，再开新的issue吧。
